/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class v2ch13_jnidemo_HelloNative */

#ifndef _Included_v2ch13_jnidemo_HelloNative
#define _Included_v2ch13_jnidemo_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     v2ch13_jnidemo_HelloNative
 * Method:    printf
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_v2ch13_jnidemo_HelloNative_printf
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
